### ISSUE TITLE
无法自动嗑石头

### ISSUE THREAD

**Issue by imaegoo** [Treetreewu/ArkNights-Farmer#3]
设备：MuMu模拟器
分辨率：1280x720

前提：

1. 没有理智合剂
2. 没有足够理智

操作步骤：

1. +刷图
2. √自动使用理智合剂
3. √自动嗑石头
4. 次数0
5. 确定
6. 开始

现象：
1. 自动点击：开始作战
2. 自动点击：使用理智合剂恢复
3. 自动点击：返回
4. 报错
```
 (。・∀・)ノ[1]Exception in thread Thread-57:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "tasks.py", line 352, in _run_tasks
  File "tasks.py", line 347, in _run_tasks
  File "tasks.py", line 142, in farm
  File "utils.py", line 126, in touch_image
  File "site-packages\airtest\utils\logwraper.py", line 71, in wrapper
  File "site-packages\airtest\core\api.py", line 260, in touch
  File "site-packages\airtest\utils\logwraper.py", line 71, in wrapper
  File "site-packages\airtest\core\cv.py", line 77, in loop_find
airtest.core.error.TargetNotFoundError: 'Picture Template(E:\\Game\\ArkNights Farmer-V2.1.0\\image/start1.png) not found in screen'
```

如果在脚本点击“使用理智合剂恢复”时，人工切回“使用源石恢复”的tab，脚本会嗑石头。

**Comment by imaegoo** [comment]
Screen record:
[bandicam 2020-05-03 08-41-32-334.zip](https://github.com/Treetreewu/ArkNights-Farmer/files/4569411/bandicam.2020-05-03.08-41-32-334.zip)

**Comment by Treetreewu** [comment]
V2.1.1 已修复（大概
